// Generated by jextract

package com.ustermetrics.clarabel4j.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef ClarabelDefaultSolution_f64 ClarabelDefaultSolution
 * }
 */
public class ClarabelDefaultSolution extends ClarabelDefaultSolution_f64 {

    ClarabelDefaultSolution() {
        // Should not be called directly
    }
}

